# Generated by Django 3.0.10 on 2021-06-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20210607_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dis_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣价'),
        ),
    ]
