# Generated by Django 3.0.10 on 2021-06-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20210607_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dis_price',
        ),
    ]
