# Generated by Django 3.0.10 on 2021-06-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_product_dis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dic_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'), max_digits=10, verbose_name='限时折扣'),
        ),
    ]
