# Generated by Django 3.0.10 on 2021-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_product_dic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='活动名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dic_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='限时折扣'),
        ),
    ]
