# Generated by Django 3.0.10 on 2021-06-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20210607_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dic_price',
        ),
    ]
